export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED";
export const FETCH_PRODUCTS_REJECTED = "FETCH_PRODUCTS_REJECTED";
export const FETCH_PRODUCTS_CANCEL = "FETCH_PRODUCTS_CANCEL";

export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const ADD_PRODUCT_CART_PENDING = "ADD_PRODUCT_CART_PENDING";
export const ADD_PRODUCT_CART_FULFILLED = "ADD_PRODUCT_CART_FULFILLED";
export const ADD_PRODUCT_CART_REJECTED = "ADD_PRODUCT_CART_REJECTED";

export const UPDATE_PRODUCT_CART = "UPDATE_PRODUCT_CART"

export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const DELETE_PRODUCT_CART_PENDING = "DELETE_PRODUCT_CART_PENDING";
export const DELETE_PRODUCT_CART_FULFILLED = "DELETE_PRODUCT_CART_FULFILLED";
export const DELETE_PRODUCT_CART_REJECTED = "DELETE_PRODUCT_CART_REJECTED";
